# Generated by Django 5.2 on 2025-05-01 04:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binder', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCardInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.CharField(max_length=100)),
                ('date_obtained', models.DateField(blank=True, null=True)),
                ('method_obtained', models.CharField(blank=True, choices=[('', 'Select a method'), ('E', 'Ebay'), ('S', 'Store'), ('P', 'Pokemon Center'), ('O', 'Other')], max_length=1, null=True)),
                ('grade', models.CharField(blank=True, choices=[('', 'Select an option'), ('Y', 'Yes'), ('N', 'No')], max_length=1, null=True)),
                ('price_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('comments', models.TextField(blank=True, max_length=100, null=True)),
                ('binder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='binder.binder')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
