# Generated by Django 5.2 on 2025-05-01 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binder', '0002_usercardinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercardinfo',
            name='graded',
            field=models.CharField(blank=True, choices=[('', 'Select an option'), ('Y', 'Yes'), ('N', 'No')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='usercardinfo',
            name='grade',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
    ]
