# Generated by Django 5.2 on 2025-05-02 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binder', '0003_usercardinfo_graded_alter_usercardinfo_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercardinfo',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
