# Generated by Django 5.2 on 2025-05-02 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binder', '0004_usercardinfo_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercardinfo',
            name='img_url_large',
            field=models.URLField(blank=True, null=True),
        ),
    ]
