# Generated by Django 5.2 on 2025-05-02 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binder', '0005_usercardinfo_img_url_large'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercardinfo',
            name='img_url_small',
            field=models.URLField(blank=True, null=True),
        ),
    ]
