# Generated by Django 5.2 on 2025-05-06 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binder', '0006_usercardinfo_img_url_small'),
    ]

    operations = [
        migrations.AddField(
            model_name='binder',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
